replaceitem entity @a[tag=!ecu1] slot.enderchest 3 barrier
replaceitem entity @a[tag=!ecu1] slot.enderchest 4 barrier
replaceitem entity @a[tag=!ecu2] slot.enderchest 5 barrier
replaceitem entity @a[tag=!ecu2] slot.enderchest 6 barrier
replaceitem entity @a slot.enderchest 7 barrier
replaceitem entity @a slot.enderchest 8 barrier
replaceitem entity @a slot.enderchest 9 barrier
replaceitem entity @a slot.enderchest 10 barrier
replaceitem entity @a slot.enderchest 11 barrier
replaceitem entity @a slot.enderchest 12 barrier
replaceitem entity @a slot.enderchest 13 barrier
replaceitem entity @a slot.enderchest 14 barrier
replaceitem entity @a slot.enderchest 15 barrier
replaceitem entity @a slot.enderchest 16 barrier
replaceitem entity @a slot.enderchest 17 barrier
replaceitem entity @a slot.enderchest 18 barrier
replaceitem entity @a slot.enderchest 19 barrier
replaceitem entity @a slot.enderchest 20 barrier
replaceitem entity @a slot.enderchest 21 barrier
replaceitem entity @a slot.enderchest 22 barrier
replaceitem entity @a slot.enderchest 23 barrier
replaceitem entity @a slot.enderchest 24 barrier
replaceitem entity @a slot.enderchest 25 barrier
replaceitem entity @a slot.enderchest 26 barrier